parameters:
   liip_terawurfl.configs:
      cache_enable: ~
      capability_filter: ~
      datadir: data/
      db:
          connector: ~
          host:  ~
          pass: ~
          schema: ~
          user: ~
      log:
          file: ~
          level: ~ #PHP loglevel constant
      memory_limit: ~
      override_memory_limit: ~
      patch:
          enable: ~
          file: ~
      simple_desktop_engine_enable: ~
      table_prefix: ~
      wurfl_cvs_url: ~
      wurfl_dl_url: ~
      wurfl_file: ~

services:
    liip_terawurfl.controller.default:
        class: Liip\TeraWurflBundle\Controller\DefaultController
        calls:
            - [ setContainer, [ @service_container ] ]

    liip_terawurfl.database:
        class: Liip\TeraWurflBundle\VendorInterface\DatabaseConnectors\TeraWurflDatabaseSymfony
        arguments:
            entityManager: @doctrine.orm.entity_manager

    liip_terawurfl.symfony:
        class: Liip\TeraWurflBundle\VendorInterface\TeraWurflSymfony
        arguments:
            config: @liip_terawurfl.configclass
            database: @liip_terawurfl.database

    liip_terawurfl.configclass:
        class: Liip\TeraWurflBundle\Config\TeraWurflConfigSymfony
        arguments:
            configs: %liip_terawurfl.configs%

    liip_terawurfl.wrapper:
        class: Liip\TeraWurflBundle\Helper\TeraWurflWrapper
        arguments:
            wurfl: @liip_terawurfl.symfony

    liip_terawurfl.update:
        class: Liip\TeraWurflBundle\Helper\TeraWurflUpdate
        arguments:
            config: @liip_terawurfl.configclass
            wurfl: @liip_terawurfl.symfony
