parameters:
   liip_terawurfl:
      cache_enable: true
      capability_filter: false
      datadir: data/
      db:
          connector: ~
          host:  ~
          pass: ~
          schema: ~
          user: ~
      log:
          file: wurfl.log
          level: LOG_WARNING #PHP loglevel constant
      memory_limit: 768M
      override_memory_limit: true
      patch:
          enable: true
          file: custom_web_patch.xml;web_browsers_patch.xml
      simple_desktop_engine_enable: true
      table_prefix: TeraWurfl
      wurfl_cvs_url: 'http://wurfl.cvs.sourceforge.net/%2Acheckout%2A/wurfl/xml/wurfl.xml'
      wurfl_dl_url: 'http://downloads.sourceforge.net/project/wurfl/WURFL/latest/wurfl-latest.zip'
      wurfl_file: wurfl.xml

services:
    liip_terawurfl.controller.default:
        class: Liip\TeraWurflBundle\Controller\DefaultController

    liip_terawurfl.database:
        class: Liip\TeraWurflBundle\VendorInterface\DatabaseConnectors\TeraWurflDatabase_Symfony
        arguments:
            entityManager: @doctrine.orm.entity_manager

    liip_terawurfl.symfony:
        class: Liip\TeraWurflBundle\VendorInterface\TeraWurflSymfony
        arguments:
            config: @liip_terawurfl.config
            database: @liip_terawurfl.database
