parameters:
   liip_terawurfl:
      cache_enable: ~
      capability_filter: ~
      datadir: data/
      db:
          connector: ~
          host:  ~
          pass: ~
          schema: ~
          user: ~
      log:
          file: ~
          level: ~ #PHP loglevel constant
      memory_limit: ~
      override_memory_limit: ~
      patch:
          enable: ~
          file: ~
      simple_desktop_engine_enable: ~
      table_prefix: ~
      wurfl_cvs_url: ~
      wurfl_dl_url: ~
      wurfl_file: ~

services:
    liip_terawurfl.controller.default:
        class: Liip\TeraWurflBundle\Controller\DefaultController
        calls:
            - [ setContainer, [ @service_container ] ]

    liip_terawurfl.database:
        class: Liip\TeraWurflBundle\VendorInterface\DatabaseConnectors\TeraWurflDatabase_Symfony
        arguments:
            entityManager: @doctrine.orm.entity_manager

    liip_terawurfl.symfony:
        class: Liip\TeraWurflBundle\VendorInterface\TeraWurflSymfony
        arguments:
            config: @liip_terawurfl.configclass
            database: @liip_terawurfl.database

    liip_terawurfl.configclass:
        class: Liip\TeraWurflBundle\Config\TeraWurflConfig
        arguments:
            capability_filter: %liip_terawurfl%

    liip_terawurfl.wrapper:
        class: Liip\TeraWurfl\Helper\TeraWurflHelper
        arguments:
            wurfl: @liip_terawurfl.symfony
